### ISSUE TITLE
The gradient remains 0

### ISSUE THREAD

**Issue by carry-all-coder** [tjqansthd/LapDepth-release#11]
Hi, very great work! but I met a problem when training. The output gradient remains 0 when I train on the kitti dataset(I did not change any code), have you met this problem before?

**Comment by tjqansthd** [comment]
Hi, if you don't use dense g.t, the gradient loss is determined to be zero.
As can be seen in README, in order for the loss to be able to be calculated, the Dense g.t depth dataset is required.
If you want to train using gradient loss and dense g.t is ready, insert `--use_dense_depth` command when training.
The preparation procedure for dense g.t. is presented in README. 
Since gradient loss is a contributing factor for visualization purposes, expected performance can be obtained even if training without gradient loss.

**Comment by carry-all-coder** [comment]
Thank you so much!

**Comment by carry-all-coder** [comment]
> Hi, if you don't use dense g.t, the gradient loss is determined to be zero. As can be seen in README, in order for the loss to be able to be calculated, the Dense g.t depth dataset is required. If you want to train using gradient loss and dense g.t is ready, insert `--use_dense_depth` command when training. The preparation procedure for dense g.t. is presented in README. Since gradient loss is a contributing factor for visualization purposes, expected performance can be obtained even if training without gradient loss.

Hi,  I try to write one script to get dense gt data according to the function by densedepth project but failed, do you still keep the script of processing the gt of kitti? I would appreciate it a lot if it can be provided, thank you!
