### ISSUE TITLE
How to get the real distance from depth map

### ISSUE THREAD

**Issue by fgogoto** [tjqansthd/LapDepth-release#19]
Hello,I don't understand how to get the real distance from the "out" in demo.py .What model I used is trained from KITTI.Could you please tell me how to get it ?

**Comment by tjqansthd** [comment]
Hi, sorry for the late response. In demo code, ```out = (out/out.max())*255.0``` is just for visualization as shown below,
https://github.com/tjqansthd/LapDepth-release/blob/a9516c40563dc1b45b24e48b3b473e08a7140c41/demo.py#L138


the model final output passes through the sigmoid layer and is multiplied by args.max_depth (in the case of KITTI, args.max_depth is determined to 80)
So "out" in below part just contain the real distance.
https://github.com/tjqansthd/LapDepth-release/blob/a9516c40563dc1b45b24e48b3b473e08a7140c41/demo.py#L123
(However, to obtain a true reliable depth value, the input image must be guaranteed to be a KITTI image. This is because the network has been trained to fit into the camera mounting environment on the KITTI dataset.

Thank you!

**Comment by kboris02** [comment]
Thank you for your work.

you said that:<<
(However, to obtain a true reliable depth value, the input image must be guaranteed to be a KITTI image. This is because the network has been trained to fit into the camera mounting environment on the KITTI dataset."
>>

.
If I want to have reliable depth values ​​for my own image obtained with my phone whose focal length is 22mm. Let's say an image of size 1980 × 3520 what operation should I apply to the "out" tensor?
